[project]
name = "deep-research-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.0.3",
    "langchain-community>=0.4.1",
    "langchain-google>=0.1.1",
    "langgraph>=1.0.2",
    "rich>=14.2.0",
]
